@startuml
state "//phantom" as PHANTOM_NODE_URQ #ffcccb {
  PHANTOM_NODE_URQ: (Ссылка на несуществующую локацию)
}
skinparam stateArrowColor #606060
skinparam state {
    BackgroundColor #F0F8FF
    BorderColor #A9A9A9
    FontColor #303030
    ArrowFontColor #404040
}
state "Фальшстарт" as 0
0: Нет описания
state "Старт" as 1
1: Пример текст стартовой локации
state "Дремучий лес" as 2
2: Вы в дремучем лесу
state "1" as 3
3: Вы пришли в лес
state "2" as 4 #d0f0d0
4: Вы пришли к высокой горе
state "Фальшстарт" as 5 
5: Дубликат локации, строчка 25. Нет описания
[*] --> 0
1 --> 3 : иди направо
1 --> 4 : иди налево
2 -[#CD5C5C,dotted]-> PHANTOM_NODE_URQ : [иди туда не знаю куда]
0 -[#CD5C5C,dotted]-> 1
2 -[#CD5C5C,dotted]-> PHANTOM_NODE_URQ : [dsfsdf]
3 --> 2 : [goto]
@enduml
