@startuml
state "//phantom" as PHANTOM_NODE_URQ #ffcccb {
  PHANTOM_NODE_URQ: (Ссылка на несуществующую локацию)
}
skinparam stateArrowColor #606060
skinparam state {
    BackgroundColor #F0F8FF
    BorderColor #A9A9A9
    FontColor #303030
    ArrowFontColor #404040
}
state "Фальстарт" as 0
0: Нет описания
state "Старт" as 4
4: Пример текста стартовой локации
state "Дремучий лес" as 5
5: Вы в дремучем лесу
state "1" as 6
6: Вы пришли в лес
state "2" as 7 #d0f0d0
7: Вы пришли к высокой горе
state "Lostinvane" as 9 #d0f0d0
9: Нет описания
state "Фальстарт" as 8 #ffcccb
8: [Дубликат метки, строка 28]\n\nНет описания
state "Фальстарт" as 2 #ffcccb
2: [Дубликат метки, строка 3]\n\nНет описания
state "Фальстарт" as 3 #ffcccb
3: [Дубликат метки, строка 4]\n\nНет описания
state "Фальстарт" as 1 #ffcccb
1: [Дубликат метки, строка 2]\n\nНет описания
[*] --> 0
4 --> 6 : иди направо
4 --> 7 : иди налево
5 -[#CD5C5C,dotted]-> PHANTOM_NODE_URQ : [иди туда - не знаю куда]
0 -[#CD5C5C,dotted]-> 1
1 -[#CD5C5C,dotted]-> 2
2 -[#CD5C5C,dotted]-> 3
3 -[#CD5C5C,dotted]-> 4
5 -[#CD5C5C,dotted]-> PHANTOM_NODE_URQ : [фан том]
6 --> 5 : [goto]
@enduml
